SELECT `action` AS `action`,
COUNT(CASE WHEN DAY(createdAt) = 1 THEN action END) AS `1d`,
COUNT(CASE WHEN DAY(createdAt) = 2 THEN action END) AS `2d`,
COUNT(CASE WHEN DAY(createdAt) = 3 THEN action END) AS `3d`,
COUNT(CASE WHEN DAY(createdAt) = 4 THEN action END) AS `4d`,
COUNT(CASE WHEN DAY(createdAt) = 5 THEN action END) AS `5d`,
COUNT(CASE WHEN DAY(createdAt) = 6 THEN action END) AS `6d`,
COUNT(CASE WHEN DAY(createdAt) = 7 THEN action END) AS `7d`,
COUNT(CASE WHEN DAY(createdAt) = 8 THEN action END) AS `8d`,
COUNT(CASE WHEN DAY(createdAt) = 9 THEN action END) AS `9d`,
COUNT(CASE WHEN DAY(createdAt) = 10 THEN action END) AS `10d`,
COUNT(CASE WHEN DAY(createdAt) = 11 THEN action END) AS `11d`,
COUNT(CASE WHEN DAY(createdAt) = 12 THEN action END) AS `12d`,
COUNT(CASE WHEN DAY(createdAt) = 13 THEN action END) AS `13d`,
COUNT(CASE WHEN DAY(createdAt) = 14 THEN action END) AS `14d`,
COUNT(CASE WHEN DAY(createdAt) = 15 THEN action END) AS `15d`,
COUNT(CASE WHEN DAY(createdAt) = 16 THEN action END) AS `16d`,
COUNT(CASE WHEN DAY(createdAt) = 17 THEN action END) AS `17d`,
COUNT(CASE WHEN DAY(createdAt) = 18 THEN action END) AS `18d`,
COUNT(CASE WHEN DAY(createdAt) = 19 THEN action END) AS `19d`,
COUNT(CASE WHEN DAY(createdAt) = 20 THEN action END) AS `20d`,
COUNT(CASE WHEN DAY(createdAt) = 21 THEN action END) AS `21d`,
COUNT(CASE WHEN DAY(createdAt) = 22 THEN action END) AS `22d`,
COUNT(CASE WHEN DAY(createdAt) = 23 THEN action END) AS `23d`,
COUNT(CASE WHEN DAY(createdAt) = 24 THEN action END) AS `24d`,
COUNT(CASE WHEN DAY(createdAt) = 25 THEN action END) AS `25d`,
COUNT(CASE WHEN DAY(createdAt) = 26 THEN action END) AS `26d`,
COUNT(CASE WHEN DAY(createdAt) = 27 THEN action END) AS `27d`,
COUNT(CASE WHEN DAY(createdAt) = 28 THEN action END) AS `28d`,
COUNT(CASE WHEN DAY(createdAt) = 29 THEN action END) AS `29d`,
COUNT(CASE WHEN DAY(createdAt) = 30 THEN action END) AS `30d`,
COUNT(CASE WHEN DAY(createdAt) = 31 THEN action END) AS `31d`
FROM `gates` AS `gate`
WHERE (`gate`.`idParking` = 1 OR `gate`.`idParking` = 2) AND `gate`.`createdAt` BETWEEN '1993-10-28 00:00:00' AND '1993-11-27 23:59:59'
GROUP BY `action`;
